# Generated by Django 5.2.7 on 2025-10-28 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='user',
            new_name='movie',
        ),
    ]
