# Generated by Django 5.2.7 on 2025-10-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_user_about_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='bg',
            field=models.FileField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
