# Generated by Django 5.2.7 on 2025-10-29 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_about_bg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Abouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg', models.FileField(blank=True, null=True, upload_to='upload/')),
                ('description', models.TextField(max_length=100)),
                ('img', models.FileField(blank=True, null=True, upload_to='upload/')),
                ('imgname', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.movie')),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.type')),
            ],
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
