# Generated by Django 5.2.7 on 2025-10-29 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_type_abouts_delete_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast', models.FileField(blank=True, null=True, upload_to='upload/')),
                ('castname', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('crewname', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='abouts',
            name='types',
        ),
        migrations.RemoveField(
            model_name='abouts',
            name='img',
        ),
        migrations.RemoveField(
            model_name='abouts',
            name='imgname',
        ),
        migrations.AddField(
            model_name='abouts',
            name='casts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cast'),
        ),
        migrations.AddField(
            model_name='abouts',
            name='crews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.crew'),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
