# Generated by Django 5.2.7 on 2025-10-29 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cast_crew_remove_abouts_types_remove_abouts_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abouts',
            name='casts',
        ),
        migrations.RemoveField(
            model_name='abouts',
            name='crews',
        ),
        migrations.AddField(
            model_name='cast',
            name='about',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.abouts'),
        ),
        migrations.AddField(
            model_name='crew',
            name='about',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.abouts'),
        ),
    ]
