# Generated by Django 5.2.7 on 2025-10-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_abouts_casts_remove_abouts_crews_cast_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouts',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
